Applied MAFALDA prompt templates to LLaMA3-Instruct
changelog

- REFACTORINGS (for fork and branch-level convenience):
run_new_experiments.sh -> run_experiments.sh
valid_model_ids 			-> valid_models
... see diff for details

- debugging of fork-isolated errors:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/administrator/code_projects/Fallacy_Detection_Language_Technology_Project/logs/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF_8B_4-bit_level_2.log'
(the file name had a '/' which was interpreted as leading to a subdir)

- Removed redundant functionality which is not the goal of this project.

- optimized bandwidth utilization for model downloads by replacing urllib.request with wrappers of huggingface_hub.hf_hub_download

- debugging of errors and warnings inherited from MAFALDA, e.g.:
error in line 29 of cli.py: split method is called on an object of class LLaMABasedQuantizedModel (should be str representing the model name)

TODO:

- add GGUF config of google/gemma-7b-it at https://huggingface.co/google/gemma-7b-it-GGUF to appropriate source in /classification_models

- add support for gemma-7b to run_experiments.sh

- migrate prompt templates from /cache/prompting to /src/experiments_pipelines